spring:
  application:
    name: pavon_alexander_shipflow

  datasource:
    url: jdbc:postgresql://localhost:5432/shipflow_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
